version: "3.9"
services:
  postgres:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: "ddhwdb"
      POSTGRES_USER: "gregory"
      POSTGRES_PASSWORD: "pgpwd4dd"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
